image: atlassian/default-image:2

test: &test
  step:
    name: Test
    script:
      - npm install -g bats
      - chmod a+x test/*.bats
      - bats test/test.bats
    services:
      - docker

push: &push
  step:
    name: Push and Tag
    deployment: Production
    image: python:3.7
    script:
      - pip install semversioner==0.*
      - chmod a+x bin/release.sh
      - ./bin/release.sh $DOCKERHUB_NAMESPACE/$BITBUCKET_REPO_SLUG
    services:
      - docker

pipelines:
  default:
    - <<: *test
  branches:
    master:
      - <<: *test
      - <<: *push
